### ISSUE TITLE
sync Google photos

### ISSUE THREAD

**Issue by wojta95** [alex3305/home-assistant-addons#25] opened 2021-09-04 21:08 UTC
Hi,

would it be possible to allow not just for upload, but for download as well? Rclone has native Google photos synchronisation support and it would be great to be able to use it with Home assistant os. The command syntax is much more simple as you don't have to manage old repositories and so on...
`rclone sync [source] [destination]`

Thanks!

**Comment by alex3305** [comment] 2021-09-10 11:52
Hi @wojta95,

Thanks for your interest in this add-on. 

I'm closing this, because it is a duplicate of #23. To be brutally honest with you I have no interest in developing this feature right now. Personally I use this add-on only for syncing backups to remotes. This is also described in the documentation:

> This add-on can only be used to sync your Home Assistant files (like snapshots) to a remote.

However, I am still looking for ways to simplify the usage of the rclone add-on, since currently it's quite a pain to set up. I have looked into the [rclone gui](https://rclone.org/gui/) and [Duplicati](https://www.duplicati.com/) to achieve this. But last time I looked into it (about 3 months ago) I decided it still was way to complicated to set up as a Home Assistant add-on.

I can only ask you to keep your eye on this repository for upcoming updates. And I will try to ping you when I have one. Thanks again for creating this issue.

**Closed by alex3305** 2021-09-10 11:52 UTC
Labels: enhancement, rclone
